POST  http://localhost:3010/UpdateShops
Content-Type: application/json

{
    "user": "MM",
    "Name": "Reliance",
    "C_no": "2222222222",
    "Email": "this@this.com",
    "Address": "Hello World",
    "Shop_id": 2
}